### ISSUE TITLE
TLS 1.0 & TLS 1.1 have reached end of life

### ISSUE THREAD

**Issue by Rottonpeech** [spritsail/nzbhydra#4]
As of Janauary 2020 TLS 1.0 & TLS 1.1 have reached end of life and are no longer supported. 
Many index providers which only allow SSL communications on TLS 1.2 and above (as should all websites in which you have secure communications with)

I am guessing this has something to do with the insane amount of error i get in my logs: 

Error while communicating with indexer: org.nzbhydra.indexers.exceptions.IndexerUnreachableException: Error while communicating with indexer <insert indexer here>. Server returned: java.net.UnknownHostException: <insert indexer uri here>

Any thoughts?

**Comment by frebib** [comment]
https://docs.oracle.com/javase/10/docs/api/java/net/UnknownHostException.html
`java.net.UnknownHostException` is an indication that either your indexer DNS is broken/missing, or your container DNS resolver is broken.
fwiw this has nothing to do with TLS. Anything still using <1.2 needs to die in a fire

I'd suggest checking your resolver config `cat /etc/resolv.conf` and checking DNS resolution is working inside your container: `ping yourindexer.com`.

Either way, I'm pretty sure this is more a configuration issue than a problem with the container

**Comment by Rottonpeech** [comment]
Yeah im sorry I was half asleep and not paying attention. Please disregard
